### PR TITLE
solving issue 42

### LINKED ISSUE #42: Suggestion from Jone
refactor into a separate function that takes TMB_DRUP and returns the generated string. Would be a nice candidate for starting to add unit testing to the project.

https://github.com/InPreD/PRONTO/pull/36#discussion_r1584919604
https://github.com/InPreD/PRONTO/pull/36#discussion_r1611669750

### PR DESCRIPTION
**Pull request by marrip**
Closes #42 

I refactored the code in question into a small function which I put in the pronto module and wrote a unit test. test job was also added to the CI. I replaced the code block with the function in the main script.

### CODE REVIEW

**Comment by marrip** [comment]
@xiaoliz0 @inful I cannot add reviewers as this is not my repository. Xiaoli, could you please add yourself and Jone as reviewers? Also would it be possible to give me access to the repo so I can do simple things in the repo like opening PRs from issues and adding reviewers. That woul be nice ☺️

**Comment by xiaoliz0** [comment]
> @xiaoliz0 @inful I cannot add reviewers as this is not my repository. Xiaoli, could you please add yourself and Jone as reviewers? Also would it be possible to give me access to the repo so I can do simple things in the repo like opening PRs from issues, adding reviewers and start github actions. That woul be nice ☺️

I have added Jone and myself as reviewers and I also give you the write access to this repository now. Let me know if it is not enough. :)

**Comment by marrip** [comment]
> > @xiaoliz0 @inful I cannot add reviewers as this is not my repository. Xiaoli, could you please add yourself and Jone as reviewers? Also would it be possible to give me access to the repo so I can do simple things in the repo like opening PRs from issues, adding reviewers and start github actions. That woul be nice ☺️
> 
> I have added Jone and myself as reviewers and I also give you the write access to this repository now. Let me know if it is not enough. :)

looks like it works as expected. I see that the action is triggered in my own fork of the repo which makes sense so you can check [there](https://github.com/marrip/PRONTO/actions) that the tests perform as expected.

**Comment by marrip** [comment]
are there any comments? If not, you can just approve 😉

**Comment by xiaoliz0** [comment]
> are there any comments? If not, you can just approve 😉

Since the changed also need to be tested by other nodes I think. I will make a new release for the current scripts before merge.

**Comment by marrip** [comment]
> > are there any comments? If not, you can just approve 😉
> 
> Since the changed also need to be tested by other nodes I think. I will make a new release for the current scripts before merge.

Maybe we can ask all nodes to provide some kind of test input for pronto to be able to perform a test directly when we develop to make sure pronto still works when we change things? Otherwise, it might take a long time to implement changes and continue development. What do you think?

**Comment by xiaoliz0** [comment]
> > > are there any comments? If not, you can just approve 😉
> > 
> > 
> > Since the changed also need to be tested by other nodes I think. I will make a new release for the current scripts before merge.
> 
> Maybe we can ask all nodes to provide some kind of test input for pronto to be able to perform a test directly when we develop to make sure pronto still works when we change things? Otherwise, it might take a long time to implement changes and continue development. What do you think?

We do have some testing data in GitHub, but it is also good to have some testings from other nodes when we have some changes. Maybe we could discuss this in the next meeting? :)

**Pull request merged**
